language: node_js
node_js:
    - "10"
install:
    - npm install
script:
    - npm run build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    repo: sajax/irsdkdocs
    keep-history: true
    on:
        branch: master
